public class RandomContactFactory {
    public static List<Contact> generateRandomContacts(Integer numofContacts,String LastNameGen){
        List<Contact> con= new List<Contact>();
        for(Integer i=0;i<numofContacts;i++){
            LastNameGen='Test'+i;
            Contact a=new Contact(FirstName=LastNameGen,LastName=LastNameGen);
            con.add(a);
        }
        return con;
    }

}